server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hisense?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #如果没有表，就创建；若存在，则更新
    properties:
      hibernate.format_sql: true  #格式化sql
